//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.22 at 11:27:57 PM CEST 
//

package com.limitless.audio.core.xml;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for channelType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="channelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}title"/>
 *         &lt;element ref="{}link"/>
 *         &lt;element ref="{}language"/>
 *         &lt;element ref="{}description"/>
 *         &lt;element ref="{}pubDate"/>
 *         &lt;element name="image" type="{}imageType"/>
 *         &lt;element ref="{}copyright"/>
 *         &lt;element ref="{}subtitle"/>
 *         &lt;element ref="{}summary"/>
 *         &lt;element name="item" type="{}itemType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "channelType", propOrder = { "title", "link", "language",
		"description", "pubDate", "image", "copyright", "subtitle", "summary",
		"item" })
public class ChannelType {

	@XmlElement(required = true)
	protected String title;
	@XmlElement(required = true)
	protected String link;
	@XmlElement(required = true)
	protected String language;
	@XmlElement(required = true)
	protected String description;
	@XmlElement(required = true)
	protected String pubDate;
	@XmlElement(required = true)
	protected ImageType image;
	@XmlElement(required = true)
	protected String copyright;
	@XmlElement(required = true)
	protected String subtitle;
	@XmlElement(required = true)
	protected String summary;
	@XmlElement(required = true)
	protected List<ItemType> item;

	/**
	 * Gets the value of the title property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * Sets the value of the title property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTitle(String value) {
		this.title = value;
	}

	/**
	 * Gets the value of the link property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLink() {
		return link;
	}

	/**
	 * Sets the value of the link property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLink(String value) {
		this.link = value;
	}

	/**
	 * Gets the value of the language property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLanguage() {
		return language;
	}

	/**
	 * Sets the value of the language property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLanguage(String value) {
		this.language = value;
	}

	/**
	 * Gets the value of the description property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescription(String value) {
		this.description = value;
	}

	/**
	 * Gets the value of the pubDate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPubDate() {
		return pubDate;
	}

	/**
	 * Sets the value of the pubDate property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPubDate(String value) {
		this.pubDate = value;
	}

	/**
	 * Gets the value of the image property.
	 * 
	 * @return possible object is {@link ImageType }
	 * 
	 */
	public ImageType getImage() {
		return image;
	}

	/**
	 * Sets the value of the image property.
	 * 
	 * @param value
	 *            allowed object is {@link ImageType }
	 * 
	 */
	public void setImage(ImageType value) {
		this.image = value;
	}

	/**
	 * Gets the value of the copyright property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCopyright() {
		return copyright;
	}

	/**
	 * Sets the value of the copyright property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCopyright(String value) {
		this.copyright = value;
	}

	/**
	 * Gets the value of the subtitle property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubtitle() {
		return subtitle;
	}

	/**
	 * Sets the value of the subtitle property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubtitle(String value) {
		this.subtitle = value;
	}

	/**
	 * Gets the value of the summary property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSummary() {
		return summary;
	}

	/**
	 * Sets the value of the summary property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSummary(String value) {
		this.summary = value;
	}

	/**
	 * Gets the value of the item property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the item property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getItem().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link ItemType }
	 * 
	 * 
	 */
	public List<ItemType> getItem() {
		if (item == null) {
			item = new ArrayList<ItemType>();
		}
		return this.item;
	}

}
