//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.22 at 11:27:57 PM CEST 
//

package com.limitless.audio.core.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="channel" type="{}channelType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;enumeration value="2.0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "channel" })
@XmlRootElement(name = "rss")
public class Rss {

	@XmlElement(required = true)
	protected ChannelType channel;
	@XmlAttribute(name = "version", required = true)
	protected String version;

	/**
	 * Gets the channel.
	 * 
	 * @return object is {@link ChannelType }
	 * 
	 */
	public ChannelType getChannel() {
		return channel;
	}

	/**
	 * Sets the channel.
	 * 
	 * @param value
	 *            allowed object is {@link ChannelType }
	 * 
	 */
	public void setChannel(ChannelType value) {
		this.channel = value;
	}

	/**
	 * Gets the value of the RSS version property.
	 * 
	 * @return {@link String }
	 * 
	 */
	public String getVersion() {
		return version;
	}

}
